### ISSUE TITLE
Listen for onPaste or onChange event for pasted text

### ISSUE THREAD

**Issue by bvaughn** [pelhage/categoreact#1]
By listening to key-down only, you miss a potential (although probably uncommon) source of input- pasted text.

For example, if I paste "a,b,c" into the demo page and then type ","- I get a single tag created for "a,b,c" instead of 3 tags ("a", "b", and "c"). I would expect that pasting "a,b,c" into the input would create 2 tags ("a" and "b") and leave "c" as the remaining input text.

Anyway, just thought I'd share this. The component looks nice! 😄

**Comment by pelhage** [comment]
Fixed! https://github.com/pelhage/categoreact/commit/9e683c529cf7b5a2f20786966f8e92d4ca077f8c

Thanks for the awesome feedback!

**Comment by bvaughn** [comment]
Nice work!
